---
- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present

- name: Ensure HTTPS APT transport for Docker repository
  apt:
    name: apt-transport-https
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker package
  apt:
    name: docker-engine
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Add vagrant user to docker group
  user:
    name:   vagrant
    groups: docker
    append: yes
