---
- name: install dependencies
  apt:
    name: apt-transport-https
    state: present

- name: install apt repository key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: '68576280'
    state: present

- name: install apt deb repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: install apt deb-src repository
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    update_cache: yes
    state: present

- name: install nodejs
  apt:
    name: nodejs
    state: present

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
